### ISSUE TITLE
Unable to Submit Files

### ISSUE THREAD

**Issue by wesleyboar** [avryhof/djangocms-forms#14]
I am unable to submit files on a form created with this plugin.

Does this feature have any known issues? (I did not find any reported at [mishbahr/djangocms-forms](https://github.com/mishbahr/djangocms-forms).)

- The image I tried was a 628 KB `.png`.
- Other equally small images failed also.
- My [django setting for file size is 20MB](https://github.com/TACC/Core-CMS/blob/1d88c35/taccsite_cms/settings.py#L451-L457).

<details open><summary>This is the error I copied the first time I saw it:</summary>

> AttributeError at /forms/submit/
```
  File "/opt/pysetup/.venv/src/djangocms-forms-maintained/djangocms_forms/fields.py", line 42, in clean
    if uploaded_file._size > self.max_upload_size:
AttributeError: 'InMemoryUploadedFile' object has no attribute '_size'
```

</details>
<details><summary>The server logs gave me a bit more information.</summary>

```
    if form.is_valid():
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/forms/forms.py", line 397, in _clean_fields
    value = field.clean(value, initial)
  File "/opt/pysetup/.venv/src/djangocms-forms-maintained/djangocms_forms/fields.py", line 42, in clean
    if uploaded_file._size > self.max_upload_size:
AttributeError: 'InMemoryUploadedFile' object has no attribute '_size'
```

</details>

I am sorry I don't have more information to provide at the moment.

**Comment by avryhof** [comment]
Not really sure why that code is like that, but it looks like an easy fix that will carry right into Django 4.1 without any issues.  I assume it's an attribute of the File class that went away, since I didn't see if in the Django 1.x code, either.

I'll just change _size to size, since that attibute is definitely set in the "UploadedFile" class that InMemoryUploadedFile inherits from.

https://docs.djangoproject.com/en/3.0/_modules/django/core/files/uploadedfile/#InMemoryUploadedFile

**Comment by avryhof** [comment]
This will show up in a release soon, but in the meantime you can install directly from this repo with pip

```pip install --upgrade git+https://github.com/avryhof/djangocms-forms.git```

or, the specific commit

```pip install git+https://github.com/avryhof/djangocms-forms.git@d8a69efd2f447ee2f940c7b6f5b8b088c9cb79ed```

**Comment by wesleyboar** [comment]
Thank you. I tested at that commit. It works! (I see uploaded file appear in Form Submissions.)

I have not tested with e-mail, but when I do test it, if any problem occurs that I can't figure out, I'll open a new ticket.
