### ISSUE TITLE
Unable to export to Excel (no attribute 'xlsx')

### ISSUE THREAD

**Issue by wesleyboar** [avryhof/djangocms-forms#8]
Similar to https://github.com/mishbahr/djangocms-forms/issues/88, I am unable to export to excel (nor yaml).

The error is an AttributeError, `'Dataset' object has no attribute 'xlsx'`.

<details><summary>Traceback</summary>

```
Environment:


Request Method: POST
Request URL: http://localhost:8000/admin/djangocms_forms/formsubmission/export/

Django Version: 2.2.27
Python Version: 3.8.13
Installed Applications:
['djangocms_admin_style',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.admin',
 'django.contrib.sites',
 'django.contrib.sitemaps',
 'taccsite_cms.django.contrib.staticfiles_custom',
 'django.contrib.messages',
 'cms',
 'menus',
 'sekizai',
 'treebeard',
 'djangocms_text_ckeditor',
 'filer',
 'easy_thumbnails',
 'meta',
 'djangocms_page_meta',
 'djangocms_column',
 'djangocms_file',
 'djangocms_link',
 'djangocms_picture',
 'djangocms_style',
 'djangocms_snippet',
 'djangocms_googlemap',
 'djangocms_transfer',
 'djangocms_video',
 'djangocms_icon',
 'djangocms_bootstrap4',
 'djangocms_bootstrap4.contrib.bootstrap4_alerts',
 'djangocms_bootstrap4.contrib.bootstrap4_badge',
 'djangocms_bootstrap4.contrib.bootstrap4_card',
 'djangocms_bootstrap4.contrib.bootstrap4_carousel',
 'djangocms_bootstrap4.contrib.bootstrap4_collapse',
 'djangocms_bootstrap4.contrib.bootstrap4_content',
 'djangocms_bootstrap4.contrib.bootstrap4_grid',
 'djangocms_bootstrap4.contrib.bootstrap4_jumbotron',
 'djangocms_bootstrap4.contrib.bootstrap4_link',
 'djangocms_bootstrap4.contrib.bootstrap4_listgroup',
 'djangocms_bootstrap4.contrib.bootstrap4_media',
 'djangocms_bootstrap4.contrib.bootstrap4_picture',
 'djangocms_bootstrap4.contrib.bootstrap4_tabs',
 'djangocms_bootstrap4.contrib.bootstrap4_utilities',
 'haystack',
 'aldryn_apphooks_config',
 'test_without_migrations',
 'djangocms_forms',
 'django.forms',
 'captcha',
 'taccsite_cms',
 'taccsite_cms.contrib.bootstrap4_djangocms_link',
 'taccsite_cms.contrib.bootstrap4_djangocms_picture',
 'taccsite_cms.contrib.taccsite_blockquote',
 'taccsite_cms.contrib.taccsite_callout',
 'taccsite_cms.contrib.taccsite_sample',
 'taccsite_cms.contrib.taccsite_offset',
 'taccsite_cms.contrib.taccsite_system_specs',
 'taccsite_cms.contrib.taccsite_system_monitor',
 'taccsite_cms.contrib.taccsite_data_list',
 'taccsite_custom.a2cps-cms',
 'taccsite_custom.apcd-cms',
 'taccsite_custom.brainmap-cms',
 'taccsite_custom.ecep-cms',
 'taccsite_custom.example-cms',
 'taccsite_custom.frontera-cms',
 'taccsite_custom.lccf-tacc',
 'taccsite_custom.neuronex-cms',
 'taccsite_custom.protx-cms',
 'taccsite_custom.sciviscolor-cms',
 'taccsite_custom.tapis-project-org',
 'taccsite_custom.texascale-org',
 'taccsite_custom.tup-cms',
 'taccsite_custom.utrc-cms']
Installed Middleware:
['cms.middleware.utils.ApphookReloadMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'cms.middleware.user.CurrentUserMiddleware',
 'cms.middleware.page.CurrentPageMiddleware',
 'cms.middleware.toolbar.ToolbarMiddleware',
 'cms.middleware.language.LanguageCookieMiddleware']



Traceback:

File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/pysetup/.venv/src/djangocms-forms-maintained/djangocms_forms/admin.py" in wrapper
  105.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/utils/decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)

File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/contrib/admin/sites.py" in inner
  223.             return view(request, *args, **kwargs)

File "/opt/pysetup/.venv/src/djangocms-forms-maintained/djangocms_forms/admin.py" in export_view
  239.                 getattr(dataset, file_type), {

Exception Type: AttributeError at /admin/djangocms_forms/formsubmission/export/
Exception Value: 'Dataset' object has no attribute 'xlsx'
```

</details>

**Comment by wesleyboar** [comment]
I wanted to overwrite the dropdown list options so that I would not show editors unusable fields, but `FORMAT_CHOICES` in [`/djangocms_forms/forms.py#L355`](https://github.com/avryhof/djangocms-forms/blob/202008311510/djangocms_forms/forms.py#L355) suggests that I cannot do this with a setting.

<details><summary>I tried to override <code>FORMAT_CHOICES</code>, but I failed.</summary>

I can not test this code because I do not where to put it nor how to load it without generating errors.

```
# Limit export format to only those that work
# https://github.com/avryhof/djangocms-forms/issues/8
# https://github.com/avryhof/djangocms-forms/blob/202008311510/djangocms_forms/forms.py#L349
FORMAT_CHOICES = (
    ("csv", _("CSV")),
    ("json", _("JSON")),
)

SubmissionExportForm.base_fields['file_type'] = forms.ChoiceField(choices=FORMAT_CHOICES, initial="csv", required=False)
```

</details>

**Comment by wesleyboar** [comment]
I tried installing tablib extras [like I suggested](https://github.com/avryhof/djangocms-forms/issues/8#issuecomment-1149189352) ([source](https://tablib.readthedocs.io/en/stable/install.html#distribute-pip)).

`pip install "tablib[all]"`
`pip install "tablib[xlsx, yaml]"`

Neither fixed the problem.

---

I propose that this repo document or summarize the steps necessary to make Excel and YAML exports work.

**Comment by avryhof** [comment]
I will take some time to look at this soon.  The main reason this fork exists is because one of our teams was using it in a project before it stopped being supported.  They weren't ready to let it go, so I just went through and made sure all of the warnings/exceptions were addressed.

I have some tools that can import/export xlsx and csv with openpyxl (and pyxlsb).  I'm a little less familiar with tablib, but it looks like it might be useful for YAML export, although I think building a JSON export wouldn't be difficult, (I have excel to dicts, and dicts to excel converters, as well as to and from csv) and going from JSON to YAML isn't too bad either.

**Comment by avryhof** [comment]
Here's my quick fix for this - https://github.com/avryhof/djangocms-forms/blob/b2b282b3b53ff05e7ed42bcbf8aa53e6b52342f4/djangocms_forms/forms.py#L355

I added **kwargs to a newly created __init__ method.  This allows you to pass in format_choices=() as a keyword arg.

I also added an option you can put in your settings.py file to make it happen globally.
```python
DJANGOCMS_FORMS_FORMAT_CHOICES = (
        ("csv", _("CSV")),
        ("json", _("JSON")),
        ("yaml", _("YAML")),
        ("xlsx", _("Microsoft Excel")),
    )
```

I look for a tuple specifically, since kwargs.get() and getattr(settings,'VAR') will default to None.

**Comment by wesleyboar** [comment]
That should work! I'll try it out today.

<details><summary>Reminder</summary>

Branch/Diff: [`avryhof:config_format_choices`](https://github.com/avryhof/djangocms-forms/compare/master...avryhof:config_format_choices)

</details>

_P.S. Thank you very much for having maintained this fork and fixing the bugs. I found no other such Django CMS plugin that lets Django CMS editor create forms (besides the broken upstream). Our primary CMS editor has many form requests, and it's far more efficient that she can build forms herself._

**Comment by avryhof** [comment]
@wesleyboar no problem.  I'll keep it going as long as I can!

**Comment by wesleyboar** [comment]
I don't think the change worked. Maybe I'm doing something wrong. Did it work for you?

I performed re-`build` of my CMS Docker container, confirmed Poetry dependency install occurred (i.e. Docker did not use cache) and re-`up`'ed them.

<details>

**Added to `_settings/form_plugin.py` (Read by `settings.py`)**
```
DJANGOCMS_FORMS_FORMAT_CHOICES = (
    ("csv", _("CSV")),
    ("json", _("JSON")),
)
```

**Changed `yproject.toml`**
From
```
djangocms-forms-maintained = { git = "https://github.com/avryhof/djangocms-forms", rev = "30f464303d317cf7a3170ad64e11ab4471b4287b" }
```
To
```
# Get 202008311510 release PLUS support for DJANGOCMS_FORMS_FORMAT_CHOICES
# https://github.com/avryhof/djangocms-forms/issues/8#issuecomment-1155288059
djangocms-forms-maintained = { git = "https://github.com/avryhof/djangocms-forms", rev = "a171bd6b7dd7a8307b4a6437fcdac169a05d6e93" }
```

![DJANGOCMS_FORMS_FIELDSETS Usage Diff](https://user-images.githubusercontent.com/62723358/173656847-9c4f971f-cc3f-4ec3-958f-54c97a0a5a0e.png)

</details>

**Comment by avryhof** [comment]
You are correct.  Sorry about that.

I had to setup a new test environment to dig further into the issue, and have a working version up in that branch.  It takes away the new init method, and just uses an if statement at the top of the form class to check if the setting has been overridden in settings

```pip install --upgrade git+https://github.com/avryhof/djangocms-forms.git@config_format_choices```

I'm also in the process of pushing a new release that will support newer versions of django (<4) and includes this fix, as well as a fix for admin_static template tags, and the removal if the url import.

```pip install --upgrade djangocms-forms-maintained```

**Comment by wesleyboar** [comment]
Hey, finally got to testing this. Thanks, it works.

I tested a commit (ab38b22) after the fix.

**Comment by avryhof** [comment]
Great!  Glad to help.
